

[[main]]
  name = "Getting Started"
  url = "/gettingstarted/"
  weight = 10

[[main]]
  name = "ClickHouse"
  url = "https://clickhouse.com/"
  weight = 20



[[docs]]
  name = "Getting Started"
  weight = 100
  identifier = "getting-started"
  url = "https://clickhouse.com/learn/docs/en/getting-started/"

[[docs]]
  name = "Inserting Data"
  weight = 130
  identifier = "insert-data"
  url = "https://clickhouse.com/learn/docs/en/insert-data/"

[[docs]]
  name = "Querying Data"
  weight = 140
  identifier = "query-data"
  url = "https://clickhouse.com/learn/docs/en/query-data/"

[[docs]]
  name = "Integrations"
  weight = 200
  identifier = "integration"
  url = "https://clickhouse.com/learn/docs/en/integration/"

[[docs]]
  name = "User Guides"
  weight = 300
  identifier = "user-guide"
  url = "https://clickhouse.com/learn/docs/en/user-guide/"

[[docs]]
  name = "Reference Guides"
  weight = 400
  identifier = "reference"
  url = "https://clickhouse.com/learn/docs/en/reference/"



[[docs]]
  name = "About ClickHouse"
  weight = 500
  identifier = "about"
  url = "https://clickhouse.com/learn/docs/en/whats-new/"