name: Deploy to Staging

on:
  workflow_dispatch:

jobs:
  deploy_to_staging:
    name: Deploy to Staging
    environment: Staging
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel to redeploy
        run: |
          curl '${{ secrets.VERCEL_HOOK }}'
