name: Deploy

on:
  workflow_dispatch:
  push:
    branches: ["va-marketing-rewrite"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        run: |
          echo 'hello world'
