name: Deploy

on:
  workflow_dispatch:
  push:
    branches: ["va-marketing-rewrite"]

jobs:
  deploy_to_staging:
    name: Deploy to Staging
    environment: Staging
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel to redeploy
        run: |
          curl '${{ env.VERCEL_HOOK }}'
